### PR TITLE
new geometry node for normal point distribution

### PR DESCRIPTION
**Pull request by jesusmb1995**
### Description
This pull request introduces a new geometry node capable of generating points based on a multivariate normal distribution. This node facilitates the placement of models, such as instances of geometry, closer to a defined center.

Key benefits of this new C++ implementation include:
- **Simplicity and Efficiency:** Compared to existing methods, this node significantly reduces complexity and enhances performance.
- **Ease of Use:** Unlike methods involving multiple geometry nodes or weights/paint, this node offers a more straightforward and smooth solution.

#### Point Cloud Generation
The new node can efficiently generate point clouds with a specified density distribution, ideal for various modeling tasks where centered clustering is desired.

node_control
node_result

#### Grass Patch Generation
Using this node, users can create grass patches with strands that are denser towards the center of the patch, gradually thinning out towards the edges. This results in a more natural and aesthetically pleasing appearance.
patch_generation

### CODE REVIEW

**Comment by DonovaneH** [comment]
Hi brotha why you're not using projects.blender.org ?

**Comment by DonovaneH** [comment]
Give me your name in projects ;)

**Comment by jesusmb1995** [comment]
> Is it you ? https://projects.blender.org/Jesus-Martin-Berlanga

Yes, thats me! Thanks for checking it out

**Comment by DonovaneH** [comment]
Come on https://blender.chat/home join the channel and ping me (@Donovane) https://blender.chat/channel/support

**Pull request closed without merging**
